# This file contains an example docker-compose configuration for running s3d.
#
# Configure s3d and register with the Sia indexer:
#   docker compose run --rm s3d login
# Then start the service:
#   docker compose up -d

services:
  s3d:
    build: .
    image: ghcr.io/siafoundation/s3d:master
    restart: unless-stopped
    ports:
      - 8000:8000/tcp
    volumes:
      - s3d:/data

volumes:
  s3d:
