[DEFAULT]
host = localhost
port = 0
is_secure = False
ssl_verify = False

[fixtures]
bucket prefix = s3d-{random}-
iam name prefix = s3-tests-
iam path prefix = /s3-tests/

[s3 main]
display_name = M. Tester
user_id = testid
email = tester@ceph.com
api_name = default
access_key = 0555b35654ad1656d804
secret_key = h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhwluN30JaT3Q==

[s3 alt]
display_name = john.doe
email = john.doe@example.com
user_id = 56789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234
access_key = NOPQRSTUVWXYZABCDEFG
secret_key = nopqrstuvwxyzabcdefghijklmnabcdefghijklm

[s3 tenant]
display_name = testx$tenanteduser
user_id = testx$9876543210abcdef0123456789abcdef0123456789abcdef0123456789abcdef
access_key = HIJKLMNOPQRSTUVWXYZA
secret_key = opqrstuvwxyzabcdefghijklmnopqrstuvwxyzab
email = tenanteduser@example.com
tenant = testx

[iam]
email = s3@example.com
user_id = 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
access_key = ABCDEFGHIJKLMNOPQRST
secret_key = abcdefghijklmnopqrstuvwxyzabcdefghijklmn
display_name = youruseridhere

[iam root]
access_key = 0555b35654ad1656d804
secret_key = h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhwluN30JaT3Q==
user_id = rootuserid
email = root@example.com

[iam alt root]
access_key = NOPQRSTUVWXYZABCDEFG
secret_key = nopqrstuvwxyzabcdefghijklmnabcdefghijklm
user_id = altrootuserid
email = altroot@example.com
