package auth_test

import (
	"bytes"
	"encoding/xml"
	"io"
	"maps"
	"net/http"
	"net/url"
	"strings"
	"testing"
	"time"

	"github.com/SiaFoundation/s3d/internal/testutil"
	"github.com/SiaFoundation/s3d/s3"
	"github.com/SiaFoundation/s3d/s3/auth"
	"github.com/SiaFoundation/s3d/s3/s3errs"
	"github.com/aws/aws-sdk-go-v2/aws"
	service "github.com/aws/aws-sdk-go-v2/service/s3"
)

func TestAnonymousCredentials(t *testing.T) {
	s3Tester := testutil.NewTester(t, testutil.WithServiceOptions(func(o *service.Options) {
		o.Credentials = aws.AnonymousCredentials{}
	}))

	// attempt to create a bucket, should fail with [ErrAccessDenied]
	err := s3Tester.CreateBucket(t.Context(), "bucket")
	testutil.AssertS3Error(t, s3errs.ErrAccessDenied, err)
}

// send sends a raw request with the given headers using the tester's HTTP
// client, asserts the status code and returns the response body.
func send(t *testing.T, s3Tester *testutil.S3Tester, method, rawURL string, header http.Header, body io.Reader, wantStatus int) []byte {
	t.Helper()
	req, err := http.NewRequestWithContext(t.Context(), method, rawURL, body)
	if err != nil {
		t.Fatal(err)
	}
	maps.Copy(req.Header, header)
	resp, err := s3Tester.Client().Options().HTTPClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatal(err)
	} else if resp.StatusCode != wantStatus {
		t.Fatalf("expected status %d, got %d: %s", wantStatus, resp.StatusCode, respBody)
	}
	return respBody
}

// assertErrorResponse asserts that body is an error response with the code of
// expected.
func assertErrorResponse(t *testing.T, expected s3errs.Error, body []byte) {
	t.Helper()
	var resp s3.ErrorResponse
	if err := xml.Unmarshal(body, &resp); err != nil {
		t.Fatalf("failed to parse error response %q: %v", body, err)
	} else if resp.Code != expected.Code {
		t.Fatalf("expected %s, got %s", expected.Code, resp.Code)
	}
}

// TestPresignedURLs checks presigned PUT, GET, HEAD and DELETE requests
// generated by the SDK.
func TestPresignedURLs(t *testing.T) {
	s3Tester := testutil.NewTester(t)
	if err := s3Tester.CreateBucket(t.Context(), "bucket"); err != nil {
		t.Fatal(err)
	}
	presigner := service.NewPresignClient(s3Tester.Client())
	expires := func(options *service.PresignOptions) {
		options.Expires = time.Hour
	}

	// upload an object using a presigned PUT
	payload := []byte("uploaded with a presigned URL")
	put, err := presigner.PresignPutObject(t.Context(), &service.PutObjectInput{
		Bucket:        aws.String("bucket"),
		Key:           aws.String("key"),
		ContentLength: aws.Int64(int64(len(payload))),
		Metadata:      map[string]string{"signed": "metadata"},
	}, expires)
	if err != nil {
		t.Fatal(err)
	}
	send(t, s3Tester, put.Method, put.URL, put.SignedHeader, bytes.NewReader(payload), http.StatusOK)

	// download it using a presigned GET
	get, err := presigner.PresignGetObject(t.Context(), &service.GetObjectInput{
		Bucket: aws.String("bucket"),
		Key:    aws.String("key"),
	}, expires)
	if err != nil {
		t.Fatal(err)
	}
	if body := send(t, s3Tester, get.Method, get.URL, get.SignedHeader, nil, http.StatusOK); !bytes.Equal(body, payload) {
		t.Fatalf("expected body %q, got %q", payload, body)
	}

	// a tampered signature is rejected
	tampered, err := url.Parse(get.URL)
	if err != nil {
		t.Fatal(err)
	}
	q := tampered.Query()
	q.Set(auth.QueryXAMZSignature, strings.Repeat("0", 64))
	tampered.RawQuery = q.Encode()
	send(t, s3Tester, get.Method, tampered.String(), get.SignedHeader, nil, http.StatusForbidden)

	head, err := presigner.PresignHeadObject(t.Context(), &service.HeadObjectInput{
		Bucket: aws.String("bucket"),
		Key:    aws.String("key"),
	}, expires)
	if err != nil {
		t.Fatal(err)
	}
	send(t, s3Tester, head.Method, head.URL, nil, nil, http.StatusOK)

	del, err := presigner.PresignDeleteObject(t.Context(), &service.DeleteObjectInput{
		Bucket: aws.String("bucket"),
		Key:    aws.String("key"),
	}, expires)
	if err != nil {
		t.Fatal(err)
	}
	send(t, s3Tester, del.Method, del.URL, nil, nil, http.StatusNoContent)
	if _, err := s3Tester.HeadObject(t.Context(), "bucket", "key", nil); err == nil {
		t.Fatal("object still exists after a presigned DELETE")
	}
}

// TestPresignedURLUnsignedHeaders checks that an unsigned x-amz-* header on a
// presigned request is rejected, otherwise a presigned PutObject could be
// turned into a CopyObject.
func TestPresignedURLUnsignedHeaders(t *testing.T) {
	s3Tester := testutil.NewTester(t)
	if err := s3Tester.CreateBucket(t.Context(), "bucket"); err != nil {
		t.Fatal(err)
	} else if err := s3Tester.AddObject("bucket", "secret.txt", []byte("secret"), nil); err != nil {
		t.Fatal(err)
	}

	// a presigned PUT only signs the host header
	presigner := service.NewPresignClient(s3Tester.Client())
	put, err := presigner.PresignPutObject(t.Context(), &service.PutObjectInput{
		Bucket: aws.String("bucket"),
		Key:    aws.String("upload.txt"),
	}, func(options *service.PresignOptions) {
		options.Expires = time.Hour
	})
	if err != nil {
		t.Fatal(err)
	}

	header := put.SignedHeader.Clone()
	header.Set("X-Amz-Copy-Source", "bucket/secret.txt")
	body := send(t, s3Tester, put.Method, put.URL, header, strings.NewReader("payload"), http.StatusForbidden)
	assertErrorResponse(t, s3errs.ErrAccessDeniedUnsignedHeaders, body)
	if _, err := s3Tester.HeadObject(t.Context(), "bucket", "upload.txt", nil); err == nil {
		t.Fatal("object was created by a rejected request")
	}
}

// TestPresignedURLRawSemicolon checks that a presigned URL with a raw ';' in a
// query parameter is served like S3 does and that the parameter reaches the
// handler, otherwise a URL presigned for one version could serve another.
func TestPresignedURLRawSemicolon(t *testing.T) {
	s3Tester := testutil.NewTester(t)
	if err := s3Tester.CreateBucket(t.Context(), "bucket"); err != nil {
		t.Fatal(err)
	} else if err := s3Tester.AddObject("bucket", "key", []byte("current version"), nil); err != nil {
		t.Fatal(err)
	}

	presigner := service.NewPresignClient(s3Tester.Client())
	get, err := presigner.PresignGetObject(t.Context(), &service.GetObjectInput{
		Bucket:    aws.String("bucket"),
		Key:       aws.String("key"),
		VersionId: aws.String("v;1"),
	}, func(options *service.PresignOptions) {
		options.Expires = time.Hour
	})
	if err != nil {
		t.Fatal(err)
	} else if !strings.Contains(get.URL, "%3B") {
		t.Fatalf("expected an escaped semicolon in %s", get.URL)
	}

	// the version doesn't exist, so both spellings have to fail the same way
	tests := []struct {
		name string
		url  string
	}{
		{"escaped", get.URL},
		{"raw", strings.ReplaceAll(get.URL, "%3B", ";")},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			body := send(t, s3Tester, get.Method, tc.url, nil, nil, http.StatusNotFound)
			assertErrorResponse(t, s3errs.ErrNoSuchVersion, body)
		})
	}
}

// TestFormEncodedBody checks that a form-encoded request body isn't mistaken
// for query parameters when building the canonical request.
func TestFormEncodedBody(t *testing.T) {
	s3Tester := testutil.NewTester(t)
	if err := s3Tester.CreateBucket(t.Context(), "bucket"); err != nil {
		t.Fatal(err)
	}

	const body = "a=1&b=2"
	if _, err := s3Tester.Client().PutObject(t.Context(), &service.PutObjectInput{
		Bucket:      aws.String("bucket"),
		Key:         aws.String("key"),
		Body:        strings.NewReader(body),
		ContentType: aws.String("application/x-www-form-urlencoded"),
	}); err != nil {
		t.Fatal(err)
	}
	got, err := s3Tester.GetObjectVersion(t.Context(), "bucket", "key", nil)
	if err != nil {
		t.Fatal(err)
	} else if string(got) != body {
		t.Fatalf("expected %q, got %q", body, got)
	}
}
